# Generated by Django 3.2.3 on 2021-08-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='empresa')),
                ('responsible', models.CharField(max_length=100, verbose_name='responsável')),
                ('department', models.CharField(max_length=50, verbose_name='setor')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('city', models.CharField(max_length=20, verbose_name='cidade')),
                ('state', models.CharField(choices=[('SP', 'São Paulo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul')], max_length=30, verbose_name='estado')),
                ('modality', models.CharField(max_length=40, verbose_name='modalidade')),
                ('n_service', models.PositiveBigIntegerField(verbose_name='n° serviços')),
                ('price', models.FloatField(verbose_name='preço')),
                ('avarage_billing', models.FloatField(verbose_name='faturamento médio')),
                ('contract_anniversary', models.DateField(verbose_name='contrato aniversário')),
                ('proposal', models.DateField(blank=True, verbose_name='proposta')),
                ('historic', models.TextField(blank=True, verbose_name='histórico')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='criação')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='atualização')),
            ],
        ),
    ]
