# Generated by Django 3.2.3 on 2021-08-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='contract_anniversary',
            field=models.DateField(null=True, verbose_name='contrato aniversário'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='criação'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='atualização'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='historic',
            field=models.TextField(blank=True, null=True, verbose_name='histórico'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='proposal',
            field=models.DateField(blank=True, null=True, verbose_name='proposta'),
        ),
    ]
