version: '3.8'
services: 

    core:
        build: ./
        command: >
            sh -c "
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - ./:/var/www
        ports: 
            - 8000:8000
            
    # database:
    #     image: postgres:9.5
    #     environment:
    #         - POSTGRES_DB=postgres
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=postgres
    #     ports:
    #         - "5470:5432"
    #     networks: 
    #         - servicenetwork
