# Generated by Django 3.2.3 on 2021-07-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=100, verbose_name='E-Mail')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('situation', models.CharField(choices=[('AT', 'ATIVO'), ('IN', 'INATIVO'), ('AR', 'AGUARDANDO RESPOSTA')], max_length=2, unique=True, verbose_name='Situação')),
            ],
        ),
    ]
